### ISSUE TITLE
404 for /static/js/simple-repository-browser.core.js

### ISSUE THREAD

**Issue by lordmauve** [simple-repository/simple-repository-browser#3]
The `simple-repository-browser.core.js` is not found after pip installing `simple-repository-browser`.

The wheel file does not contain the Javascript files:

```
$ unzip -l *.whl
Archive:  simple_repository_browser-0.5.0-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      480  2024-06-27 10:29   simple_repository_browser/__init__.py
     2659  2024-06-27 10:29   simple_repository_browser/__main__.py
     5328  2024-06-27 10:29   simple_repository_browser/_app.py
     5327  2024-06-27 10:29   simple_repository_browser/_search.py
      411  2024-06-27 14:26   simple_repository_browser/_version.py
     4850  2024-06-27 10:29   simple_repository_browser/compatibility_matrix.py
     6199  2024-06-27 10:29   simple_repository_browser/controller.py
     7847  2024-06-27 10:29   simple_repository_browser/crawler.py
      741  2024-06-27 10:29   simple_repository_browser/errors.py
    11500  2024-06-27 10:29   simple_repository_browser/fetch_description.py
     3199  2024-06-27 10:29   simple_repository_browser/fetch_projects.py
     2859  2024-06-27 10:29   simple_repository_browser/metadata_injector.py
     7802  2024-06-27 10:29   simple_repository_browser/model.py
     3379  2024-06-27 10:29   simple_repository_browser/short_release_info.py
     5510  2024-06-27 10:29   simple_repository_browser/view.py
     4022  2024-06-27 10:29   simple_repository_browser/static/images/favicon.6a76275d.ico
    12386  2024-06-27 10:29   simple_repository_browser/static/images/logo-large.svg
    12525  2024-06-27 10:29   simple_repository_browser/static/images/logo-small-single-tower.svg
    12386  2024-06-27 10:29   simple_repository_browser/static/images/logo-small.svg
     8941  2024-06-27 10:29   simple_repository_browser/static/images/python-logo-only.svg
      990  2024-06-27 10:29   simple_repository_browser/templates/base/about.html
     2478  2024-06-27 10:29   simple_repository_browser/templates/base/base.html
      578  2024-06-27 10:29   simple_repository_browser/templates/base/error.html
     2020  2024-06-27 10:29   simple_repository_browser/templates/base/index.html
      750  2024-06-27 10:29   simple_repository_browser/templates/base/page.html
    18659  2024-06-27 10:29   simple_repository_browser/templates/base/project.html
     4080  2024-06-27 10:29   simple_repository_browser/templates/base/search.html
      327  2024-06-27 10:29   simple_repository_browser/tests/__init__.py
     1786  2024-06-27 10:29   simple_repository_browser/tests/test_RequirementSequence.py
     4598  2024-06-27 10:29   simple_repository_browser/tests/test_compatibility_matrix.py
     6110  2024-06-27 10:29   simple_repository_browser/tests/test_search.py
     1912  2024-06-27 10:29   simple_repository_browser/tests/test_view.py
     1061  2024-06-27 14:26   simple_repository_browser-0.5.0.dist-info/LICENSE
      315  2024-06-27 14:26   simple_repository_browser-0.5.0.dist-info/LICENSE_HEADER
     3865  2024-06-27 14:26   simple_repository_browser-0.5.0.dist-info/METADATA
       91  2024-06-27 14:26   simple_repository_browser-0.5.0.dist-info/WHEEL
       86  2024-06-27 14:26   simple_repository_browser-0.5.0.dist-info/entry_points.txt
       26  2024-06-27 14:26   simple_repository_browser-0.5.0.dist-info/top_level.txt
     4016  2024-06-27 14:26   simple_repository_browser-0.5.0.dist-info/RECORD
---------                     -------
   172099                     39 files
```

The sdist does contain the Javascript files but does not install them into the venv.

**Comment by pelson** [comment]
Hi @lordmauve - good to hear from you. I have been meaning to contact you on the topic of `simple-repository`, but am glad to hear that you've made your own way here :smile: 

Thanks for the report. This previously worked, as mentioned in the README at https://github.com/simple-repository/simple-repository-browser?tab=readme-ov-file#development. I would guess this has got lost in the move to `pyproject.toml` only. The fact that this file is not tracked means that indeed `setuptools` won't install it unless it is in a manifest file - which we don't have. Should be an easy fix (as per https://setuptools.pypa.io/en/latest/userguide/datafiles.html#include-package-data).

**Comment by pelson** [comment]
Should be fixed by v0.5.1. Please could you confirm?

**Comment by lordmauve** [comment]
Yes, I am still interested in this. Just getting to the point of needing simple-repository-browser in our adoption of Python packaging tools. Unfortunately we've continued to invest in Artifactory as a package repository despite reservations about value, security, and feature set.

**Comment by pelson** [comment]
If you haven't already seen it, take a look at https://discuss.python.org/t/introducing-simple-repository-server-a-standards-compliant-extensible-python-package-index-server/63482.

> we've continued to invest in Artifactory as a package repository despite reservations about value, security, and feature set

All is not lost... you could put a `simple-repository-server` on top of your artifactory service, and Lo! you get PEP-658++ good-nes. Essentially treating Artifactory as the upload destination (for which it is a fairly good choice). Would happily exchange more on this in the discussion board at https://github.com/orgs/simple-repository/discussions.

**Comment by lordmauve** [comment]
I can confirm it works in 0.5.1. Thanks!

**Comment by pelson** [comment]
Thanks for checking. :+1: 

I'll be interested to hear if the default indexing strategy is what you expect - it isn't obvious what the best approach is and at present there is no configuration option to control it.
